# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection/v1/anomaly_rule_config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'detection/v1/anomaly_rule_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&detection/v1/anomaly_rule_config.proto\x12\x0c\x64\x65tection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x01\n\x11\x41nomalyRuleConfig\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65tector\x18\x04 \x01(\t\x12\x13\n\x0bparams_json\x18\x05 \x01(\t\x12.\n\x08\x62indings\x18\x06 \x03(\x0b\x32\x1c.detection.v1.ChannelBinding\x12\x10\n\x08severity\x18\x07 \x01(\t\x12\x18\n\x10\x63ooldown_seconds\x18\x08 \x01(\x05\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"]\n\x0e\x43hannelBinding\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x17\n\x0fmetric_point_id\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x11\n\tmetric_id\x18\x04 \x01(\x05\x42?\n#com.digitaldemon.detection.proto.v1B\x16\x41nomalyRuleConfigProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection.v1.anomaly_rule_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.digitaldemon.detection.proto.v1B\026AnomalyRuleConfigProtoP\001'
  _globals['_ANOMALYRULECONFIG']._serialized_start=90
  _globals['_ANOMALYRULECONFIG']._serialized_end=338
  _globals['_CHANNELBINDING']._serialized_start=340
  _globals['_CHANNELBINDING']._serialized_end=433
# @@protoc_insertion_point(module_scope)
