# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection/v1/detection_event.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'detection/v1/detection_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"detection/v1/detection_event.proto\x12\x0c\x64\x65tection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n\x0e\x44\x65tectionEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12&\n\x07\x63hannel\x18\x03 \x01(\x0b\x32\x15.detection.v1.Channel\x12\x11\n\tasset_ref\x18\x04 \x01(\t\x12/\n\x0b\x64\x65tected_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x64\x65tail\x18\x06 \x01(\t\x12\x11\n\ttenant_id\x18\x07 \x01(\t\x12\x0f\n\x07summary\x18\x08 \x01(\t\"/\n\x07\x43hannel\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tmetric_id\x18\x02 \x01(\x05\x42<\n#com.digitaldemon.detection.proto.v1B\x13\x44\x65tectionEventProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection.v1.detection_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.digitaldemon.detection.proto.v1B\023DetectionEventProtoP\001'
  _globals['_DETECTIONEVENT']._serialized_start=86
  _globals['_DETECTIONEVENT']._serialized_end=294
  _globals['_CHANNEL']._serialized_start=296
  _globals['_CHANNEL']._serialized_end=343
# @@protoc_insertion_point(module_scope)
