# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection/v1/rule_config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'detection/v1/rule_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x64\x65tection/v1/rule_config.proto\x12\x0c\x64\x65tection.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n\nRuleConfig\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x17\n\x0fmetric_point_id\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x11\n\tmetric_id\x18\x04 \x01(\x05\x12\x10\n\x08operator\x18\x05 \x01(\t\x12\x16\n\tthreshold\x18\x06 \x01(\x01H\x00\x88\x01\x01\x12\x10\n\x08severity\x18\x07 \x01(\t\x12\x18\n\x10\x63ooldown_seconds\x18\x08 \x01(\x05\x12\x11\n\ttenant_id\x18\t \x01(\t\x12.\n\nupdated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0c\n\n_thresholdB8\n#com.digitaldemon.detection.proto.v1B\x0fRuleConfigProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection.v1.rule_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.digitaldemon.detection.proto.v1B\017RuleConfigProtoP\001'
  _globals['_RULECONFIG']._serialized_start=82
  _globals['_RULECONFIG']._serialized_end=341
# @@protoc_insertion_point(module_scope)
