# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1/measurement_ingestion.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'core/v1/measurement_ingestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#core/v1/measurement_ingestion.proto\x12\x07\x63ore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n\x10MeasurementBatch\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12/\n\x0bingested_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0cmeasurements\x18\x03 \x03(\x0b\x32\x1c.core.v1.IngestedMeasurement\"a\n\x13IngestedMeasurement\x12\x11\n\tmetric_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x01\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB@\n!com.heatingplatform.core.proto.v1B\x19MeasurementIngestionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1.measurement_ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.heatingplatform.core.proto.v1B\031MeasurementIngestionProtoP\001'
  _globals['_MEASUREMENTBATCH']._serialized_start=82
  _globals['_MEASUREMENTBATCH']._serialized_end=220
  _globals['_INGESTEDMEASUREMENT']._serialized_start=222
  _globals['_INGESTEDMEASUREMENT']._serialized_end=319
# @@protoc_insertion_point(module_scope)
