[project]
name = "simulation-engine"
version = "0.1.0"
license = "MIT"
description = "Simulation Engine"
authors = [
    {name = "Sascha Kiebler", email = "saschakiebler@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
