apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heating-platform

resources:
  - namespace.yaml
  - secrets.yaml
  - timescaledb.yaml
  - kafka.yaml
  - mosquitto.yaml
  - device-management.yaml
  - ingestion-service.yaml
  - core-platform.yaml
  - notification-service.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: heating-platform
